<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analysis Report #{{ $analysis->id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }
        .result {
            font-size: 18px;
            margin: 20px 0;
            padding: 10px;
            border-radius: 5px;
        }
        .positive {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .negative {
            background-color: #dcfce7;
            color: #166534;
        }
        .details {
            margin: 20px 0;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Malaria Analysis Report</h1>
        <p>Report ID: #{{ $analysis->id }}</p>
        <p>Generated: {{ $generated_at->format('F d, Y H:i:s') }}</p>
    </div>

    <div class="result {{ $analysis->result === 'positive' ? 'positive' : 'negative' }}">
        Result: {{ ucfirst($analysis->result) }}
    </div>

    <div class="details">
        <table>
            <tr>
                <th>Analysis Date:</th>
                <td>{{ $analysis->created_at->format('F d, Y H:i:s') }}</td>
            </tr>
            <tr>
                <th>Confidence Score:</th>
                <td>{{ number_format($analysis->confidence_score, 1) }}%</td>
            </tr>
            <tr>
                <th>Processing Time:</th>
                <td>{{ $analysis->processing_time_ms }}ms</td>
            </tr>
            @if($analysis->confidence_score < 70)
            <tr>
                <th>Manual Review:</th>
                <td>Required due to low confidence score</td>
            </tr>
            @endif
        </table>

        @if($analysis->result_data)
        <h3>Detailed Analysis Results</h3>
        <table>
            @foreach(json_decode($analysis->result_data, true) as $key => $value)
            <tr>
                <th>{{ ucfirst(str_replace('_', ' ', $key)) }}:</th>
                <td>{{ is_bool($value) ? ($value ? 'Yes' : 'No') : $value }}</td>
            </tr>
            @endforeach
        </table>
        @endif
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} for {{ $user->name }}</p>
        <p>This report is confidential and intended only for authorized medical personnel.</p>
    </div>
</body>
</html>